  
"""Constants for YT-MX0404V2 component."""

DOMAIN = "yt_mx0404v2"

DEFAULT_NAME = "YT-MX0404V2"
DEFAULT_PORT = 23
DEFAULT_RECONNECT_INTERVAL = 10
DEFAULT_POLLING_INTERVAL = 3
CONNECTION_TIMEOUT = 10

CONF_INPUTS1 = "input1"
CONF_INPUTS2 = "input2"
CONF_INPUTS3 = "input3"
CONF_INPUTS4 = "input4"
DEFAULT_INPUTS1 = "Input 1"
DEFAULT_INPUTS2 = "Input 2"
DEFAULT_INPUTS3 = "Input 3"
DEFAULT_INPUTS4 = "Input 4"

